name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.tests-backend.outputs.report }}
    steps:
      - uses: actions/checkout@v7

      - name: set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25'
          cache-dependency-path: bugtracker-backend/go.sum

      - name: install junit reporter
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: execute backend unit tests
        id: tests-backend
        working-directory: ./bugtracker-backend
        run: |
          go test -json -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.txt 

          echo "## Go Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat coverage.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          go test -v 2>&1 ./... | go-junit-report -set-exit-code > test-results.xml

      - name: publish backend test report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: backend unit tests report
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit
  
  
  unit-tests-frontend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.tests-frontend.outputs.report }}
    steps:
      - uses: actions/checkout@v7

      - name: set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: bugtracker-frontend/package-lock.json
      
      - name: execute frontend unit tests
        id: tests-frontend
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test | tee full-output.txt

          echo "## Frontend Test Output" >> $GITHUB_STEP_SUMMARY
          cat full-output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat full-output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          

      - name: publish frontend test report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: frontend unit tests report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit


  create-coverage-comment:
    if: github.event_name == 'pull_request'
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Create coverage comment backend
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Go Test Coverage Report
            ```
            ${{needs.unit-tests-backend.outputs.coverage}}
            ```
      - name: Create coverage comment frontend
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Node Test Coverage Report
            ```
            ${{needs.unit-tests-frontend.outputs.coverage}}
            ```

  api-e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests-backend, unit-tests-frontend]
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: launch application
        run: |
          docker compose up --build -d
          npx wait-port http://localhost:8080/api/health -t 30000

      - name: Run Api Test
        working-directory: ./tests-api
        env:
          CI: "1"
        run: |
          npm ci
          npx playwright test

      - name: E2E api test
        working-directory: ./tests-e2e
        run: |
          npm ci
          npx playwright install
          npx playwright test

      - name: setup k6
        uses: grafana/setup-k6-action@v1
      - name: run performance testing
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./tests-perf/script.js
          flags: --out json=summary.json

      - name: shutdown Application
        run: docker compose down

      - name: upload Api test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ./tests-api/test-results/
          retention-days: 30

      - name: upload e2e test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: ./tests-e2e/test-results
          retention-days: 30
      
      - name: upload Api test playwright report into artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-playwright-report
          path: ./tests-api/playwright-report/
          retention-days: 30

      - name: upload e2e test playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-playwright-report
          path: ./tests-e2e/playwright-report/
          retention-days: 30

      - name: upload performance test raw result into artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-raw-report
          path: ./tests-perf/summary.json
          retention-days: 30
        
      - name: upload performance test Html result into artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-raw-report
          path: ./tests-perf/perf-results.html
          retention-days: 30
        

      - name: publish Api test reports
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Api test reports
          path: ./tests-api/test-results/*.xml
          reporter: jest-junit


      - name: publish e2e test reports
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: e2e test reports
          path: ./tests-e2e/test-results/*.xml
          reporter: jest-junit

      