name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25'
          cache-dependency-path: bugtracker-backend/go.sum

      - name: install junit reporter
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: execute backend unit tests
        working-directory: ./bugtracker-backend
        run: |
          go test -v 2>&1 ./... | go-junit-report -set-exit-code > test-results.xml

      - name: publish backend test report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: backend unit tests report
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit
  
  
  unit-tests-frontend:
    needs: unit-tests-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: bugtracker-frontend/package-lock.json
      
      - name: execute frontend unit tests
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test

      - name: publish frontend test report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: frontend unit tests report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit


